spring:
  application:
    name: poc-h2
    version: 1.0
  datasource:
    url: jdbc:mysql://localhost:3306/poc
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: teste22

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
server:
  port: ${SERVER_PORT:8091}
  servlet:
    context-path: /${spring.application.name}